apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordcloud
  labels:
    app: wordcloud
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordcloud
  template:
    metadata:
      labels:
        app: wordcloud
    spec:
      containers:
      # replace the repository URL with your own repository (e.g. {DockerID}/http-db-service:0.0.x for Docker Hub).
      - image: kenlomax/wordcloud:v1
        imagePullPolicy: Always
        name:  wordcloud
        ports:
        - name: http
          containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: wordcloud
  labels:
    app: wordcloud
spec:
  ports:
  - name: http
    port: 8082
  selector:
    app: wordcloud
